# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9131af0224f63ba196c205079e25dcd000f3bde60692af8c66b7aa86468ecaae8f531c589e5017a82010d7ed5d24aae8d277fffacd7b7f43a3a41eff942dc645

test:
  secret_key_base: a76d1f9dbd6f00af8cf2b39be58b9d2465ae9d43ce50a35c89423df000ac327d78a8eeb581e39b03187e69f3d4087a733f9229e18499dd4f2dafff4b9dfc28b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
